// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcNUERERwZwKnJF30mIBV2-YoQafk6zV8',
    appId: '1:440867285334:android:2ae3cd4dad1e96f82f0ef7',
    messagingSenderId: '440867285334',
    projectId: 'flutter-flavor-app-test',
    storageBucket: 'flutter-flavor-app-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1QZZ2WHcVClJKD8BqNvg_G4O1et34JPY',
    appId: '1:440867285334:ios:e5c4b9dda358f9fe2f0ef7',
    messagingSenderId: '440867285334',
    projectId: 'flutter-flavor-app-test',
    storageBucket: 'flutter-flavor-app-test.appspot.com',
    androidClientId: '440867285334-6tm80hqf4gqekjnpjtcqh57qr5mpgo0r.apps.googleusercontent.com',
    iosClientId: '440867285334-i324qd056veanr7jda2986aish07id0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFlavorTest.qa',
  );
}
